### ISSUE TITLE
eavesdrop mode completely borken

### ISSUE THREAD

**Issue by lucasdemarchi** [mavlink-router/mavlink-router#283]
eavesdrop mode was supposed to be a mode in which the endpoint receives all the messages, regardless if it was targeting it. This allows us to "spy" on all the messages going on and dump it somewhere for analysis.  This is not working - somewhere along the line we lost the checks in the endpoints for "also send the message to this endpoint if it is in eavesdrop mode" and the bind() call seems to be completely wrong, as then the port would be the source and not the destination.

**Comment by jbeyerstedt** [comment]
Do I understand it correctly, that the "eavesdropping" mode should be like port mirroring in an ethernet switch, but for all messages going through mavlink router? Or in other words, an endpoint in eavesdropping mode should output all messages going through the router?

Because that's definitely not what the documentation in [config.sample](https://github.com/mavlink-router/mavlink-router/blob/master/examples/config.sample#L77) says and not how it's currently used (because of the current behavior). But it'll explain the non-ideal naming of `targetAddress` which is more of a binding address in eavesdropping mode currently. (And therefore my argument to rework the config to have a separate binding and/or target address/port combination on each endpoint making the intention (listening or sending first) more intuitive. But maybe that's another discussion.)

**Comment by lucasdemarchi** [comment]
@jbeyerstedt handling eavesdropping as "server/udpin" was a bug. In order to be compatible what we should probably do is to declare type == eavesdropping as dreprecated and just assign another word for that behavior. "server" is probably a good one.

When/if we implement real eavesdropping mode, then we use another word to describe that behavior. Thinking about network interfaces, we can borrow the [promiscuous mode](https://en.wikipedia.org/wiki/Promiscuous_mode#:~:text=In%20computer%20networking%2C%20promiscuous%20mode,that%20the%20controller%20is%20specifically) words. Or "spy". Or indeed move it to another endpoint type: debug.
