### ISSUE TITLE
Use an endpoint for listening, but not sending commands

### ISSUE THREAD

**Issue by nirgivon** [mavlink-router/mavlink-router#345]
Hi,

Here is a scenario:
I need to have 2 UDP endpoints.

The first is a "Normal" endpoint that allows 2 way communication with the Pilot.
Used for telemetry and control.

The second is a "Listening" endpoint.
Where I allow the user to receive the incoming telemetry form the pilot, but block all incoming commands to prevent control of the aircraft.

Is this functionality supported?
Can you suggest how can I configure to get this result?

Thanks!

**Comment by jbeyerstedt** [comment]
Currently, we only have filters (by message ID, system ID or component ID) to limit, which messages will be sent on an endpoint. Since you want to block incoming data, that's not supported yet, but shouldn't be a big issue to add, either.

I would suggest to implement message filters instead of adding a single-purpose config option to block all incoming traffic because it would allow for more flexible use. You would need to use message ID or system ID zero to disallow all messages, though (sysID 0 is not allowed, msgID 0 is not used). Depending on the use case, just allowing heartbeats might be useful, too.

**Comment by jbeyerstedt** [comment]
It this doesn't work, please just comment here and I'll re-open this issue.
