### ISSUE TITLE
I see the 0 size log factory is still working full time

### ISSUE THREAD

**Issue by highfreq** [mavlink-router/mavlink-router#352]
I see 0 size log factory still working full steam ahahahah, what a joke.

Maybe before adding new functions would have been better fixing what is already there.

**Comment by khancyr** [comment]
Before criticize, please make a correct report on how this happens.

You are using an open source projects, if you want something done, you probably need to help instead of complaining and mocking people that invest time to share a project with other for free.

And if you were really into looking for a fix for this issue, you would have read that we are discussing and trying some solutions...

**Comment by highfreq** [comment]
Ma vai a fare in culo faccia di merda.

**Comment by lucasdemarchi** [comment]
Interesting how you're not using it, yet you have time to waste everyone's else time. Go use your own software that you shared with everybody and market it so people know how awesome it is.

And just because you write in Italian, it doesn't mean you can use this kind of words here.
