### ISSUE TITLE
Question - does this repository have any CI tests ?

### ISSUE THREAD

**Issue by Consti10** [mavlink-router/mavlink-router#358]
Hello,

I am one of the developers of OpenHD - I am wondering if there are some (git)-ci tests for this repository & if not, do you want any ?

Best regards,Constantin

**Comment by jbeyerstedt** [comment]
There are some unit tests and there's [routing_test.py](https://github.com/mavlink-router/mavlink-router/blob/master/tests/routing_test.py), which are run during the CI workflow. But both of them need quite some more love to really assure, that no existing functionality breaks with new PRs. In other words: The current automatic tests are just a very basic baseline.

Therefore I don't really see the benefit of adding the badge. It wouldn't hurt, but the information value is also quite low. E.g. the last time we had failing CI runs was because an `apt update` was missing before trying to install packages.

But we would really appreciate some pull requests adding more unit and integration tests. We reworked the readme in the lasts few months to actually specify the intended behavior (which mostly was the actual behavior). So it should be possible to add tests verifying the specification.
